apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-old-replicasets
  namespace: default
  labels:
    app: dsp-prod
    component: cleanup
spec:
  # Запускаем каждый час
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dsp-prod
            component: cleanup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: cleanup-service-account
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              echo "🧹 Cleaning up old ReplicaSets for dsp-prod..."
              
              # Получаем все ReplicaSets, сортируем по времени создания
              OLD_RS=$(kubectl get rs -n default -l app=dsp-prod --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | head -n -3)
              
              if [ -n "$OLD_RS" ]; then
                echo "🗑️ Deleting old ReplicaSets:"
                echo "$OLD_RS"
                echo "$OLD_RS" | xargs -r kubectl delete rs -n default
                echo "✅ Cleanup completed"
              else
                echo "ℹ️ No old ReplicaSets to clean up"
              fi
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cleanup-service-account
  namespace: default
roleRef:
  kind: Role
  name: cleanup-role
  apiGroup: rbac.authorization.k8s.io 