apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dsp-prod-istio-tls
  namespace: istio-system
  labels:
    app: dsp-prod
    environment: production
  annotations:
    cert-manager.io/revision-history-limit: "3"
spec:
  secretName: dsp-prod-istio-tls
  duration: 2160h    # 90 дней (максимум для Let's Encrypt)
  renewBefore: 720h  # Обновлять за 30 дней до истечения
  dnsNames:
  - gyber.org
  - www.gyber.org
  commonName: gyber.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always  # Всегда генерировать новый ключ при обновлении
  usages:
  - digital signature
  - key encipherment
  - server auth
  secretTemplate:
    annotations:
      dsp.gyber.org/certificate-name: "dsp-prod-istio-tls"
      dsp.gyber.org/issuer-name: "letsencrypt-production"
    labels:
      app: dsp-prod
      environment: production
      dsp.gyber.org/certificate-name: "dsp-prod-istio-tls" 