apiVersion: batch/v1
kind: CronJob
metadata:
  name: cert-monitor
  namespace: default
spec:
  schedule: "0 9 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: cert-monitor
          containers:
          - name: cert-checker
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              apk add --no-cache jq
              echo "🔍 Checking certificates..."
              kubectl get certificates -A -o json | jq -r '.items[] | select(.status.notAfter != null) | "\(.metadata.namespace)/\(.metadata.name) \(.status.notAfter)"'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-monitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-monitor
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-monitor
subjects:
- kind: ServiceAccount
  name: cert-monitor
  namespace: default
roleRef:
  kind: ClusterRole
  name: cert-monitor
  apiGroup: rbac.authorization.k8s.io 