apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dsp-stage-istio-tls
  namespace: default
spec:
  secretName: dsp-stage-istio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - stage.dsp.build.infra.gyber.org 