/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as TeamsIndexImport } from './routes/teams/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as InvitesIndexImport } from './routes/invites/index'
import { Route as UsersUserDetailsIndexImport } from './routes/users/userDetails/index'
import { Route as TeamsCreateTeamIndexImport } from './routes/teams/createTeam/index'
import { Route as ProjectsCreateProjectIndexImport } from './routes/projects/createProject/index'
import { Route as InvitesCreateInvitesIndexImport } from './routes/invites/createInvites/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const InvitesIndexRoute = InvitesIndexImport.update({
  id: '/invites/',
  path: '/invites/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserDetailsIndexRoute = UsersUserDetailsIndexImport.update({
  id: '/users/userDetails/',
  path: '/users/userDetails/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsCreateTeamIndexRoute = TeamsCreateTeamIndexImport.update({
  id: '/teams/createTeam/',
  path: '/teams/createTeam/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsCreateProjectIndexRoute = ProjectsCreateProjectIndexImport.update(
  {
    id: '/projects/createProject/',
    path: '/projects/createProject/',
    getParentRoute: () => rootRoute,
  } as any,
)

const InvitesCreateInvitesIndexRoute = InvitesCreateInvitesIndexImport.update({
  id: '/invites/createInvites/',
  path: '/invites/createInvites/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/invites/': {
      id: '/invites/'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/invites/createInvites/': {
      id: '/invites/createInvites/'
      path: '/invites/createInvites'
      fullPath: '/invites/createInvites'
      preLoaderRoute: typeof InvitesCreateInvitesIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/createProject/': {
      id: '/projects/createProject/'
      path: '/projects/createProject'
      fullPath: '/projects/createProject'
      preLoaderRoute: typeof ProjectsCreateProjectIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/createTeam/': {
      id: '/teams/createTeam/'
      path: '/teams/createTeam'
      fullPath: '/teams/createTeam'
      preLoaderRoute: typeof TeamsCreateTeamIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/userDetails/': {
      id: '/users/userDetails/'
      path: '/users/userDetails'
      fullPath: '/users/userDetails'
      preLoaderRoute: typeof UsersUserDetailsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invites': typeof InvitesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/users': typeof UsersIndexRoute
  '/invites/createInvites': typeof InvitesCreateInvitesIndexRoute
  '/projects/createProject': typeof ProjectsCreateProjectIndexRoute
  '/teams/createTeam': typeof TeamsCreateTeamIndexRoute
  '/users/userDetails': typeof UsersUserDetailsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invites': typeof InvitesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/users': typeof UsersIndexRoute
  '/invites/createInvites': typeof InvitesCreateInvitesIndexRoute
  '/projects/createProject': typeof ProjectsCreateProjectIndexRoute
  '/teams/createTeam': typeof TeamsCreateTeamIndexRoute
  '/users/userDetails': typeof UsersUserDetailsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/invites/': typeof InvitesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/invites/createInvites/': typeof InvitesCreateInvitesIndexRoute
  '/projects/createProject/': typeof ProjectsCreateProjectIndexRoute
  '/teams/createTeam/': typeof TeamsCreateTeamIndexRoute
  '/users/userDetails/': typeof UsersUserDetailsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invites'
    | '/projects'
    | '/teams'
    | '/users'
    | '/invites/createInvites'
    | '/projects/createProject'
    | '/teams/createTeam'
    | '/users/userDetails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invites'
    | '/projects'
    | '/teams'
    | '/users'
    | '/invites/createInvites'
    | '/projects/createProject'
    | '/teams/createTeam'
    | '/users/userDetails'
  id:
    | '__root__'
    | '/'
    | '/invites/'
    | '/projects/'
    | '/teams/'
    | '/users/'
    | '/invites/createInvites/'
    | '/projects/createProject/'
    | '/teams/createTeam/'
    | '/users/userDetails/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitesIndexRoute: typeof InvitesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  InvitesCreateInvitesIndexRoute: typeof InvitesCreateInvitesIndexRoute
  ProjectsCreateProjectIndexRoute: typeof ProjectsCreateProjectIndexRoute
  TeamsCreateTeamIndexRoute: typeof TeamsCreateTeamIndexRoute
  UsersUserDetailsIndexRoute: typeof UsersUserDetailsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitesIndexRoute: InvitesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  InvitesCreateInvitesIndexRoute: InvitesCreateInvitesIndexRoute,
  ProjectsCreateProjectIndexRoute: ProjectsCreateProjectIndexRoute,
  TeamsCreateTeamIndexRoute: TeamsCreateTeamIndexRoute,
  UsersUserDetailsIndexRoute: UsersUserDetailsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/invites/",
        "/projects/",
        "/teams/",
        "/users/",
        "/invites/createInvites/",
        "/projects/createProject/",
        "/teams/createTeam/",
        "/users/userDetails/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/invites/": {
      "filePath": "invites/index.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    },
    "/teams/": {
      "filePath": "teams/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/invites/createInvites/": {
      "filePath": "invites/createInvites/index.tsx"
    },
    "/projects/createProject/": {
      "filePath": "projects/createProject/index.tsx"
    },
    "/teams/createTeam/": {
      "filePath": "teams/createTeam/index.tsx"
    },
    "/users/userDetails/": {
      "filePath": "users/userDetails/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
