apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gprod-prod-certificate
  namespace: prod-gprod
spec:
  secretName: gprod-prod-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - api.gprod.build.infra.gyber.org
  duration: 2160h # 90 дней
  renewBefore: 360h # 15 дней до истечения
  subject:
    organizations:
      - GPROD Production
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth 